{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homer.fullname" . }}-config
data:
  {{ .Values.config.file }}: |-
{{ (.Files.Get .Values.config.file) | indent 4 }}
binaryData:
  {{ .Values.logo.file }}: |-
{{ (.Files.Get .Values.logo.file) | b64enc | indent 4 }}
{{- end }}
